apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: exam-system
type: Opaque
data:
  # root:root (base64 encoded)
  mysql-root-password: cm9vdA==
  mysql-username: cm9vdA==
  mysql-password: cm9vdA==
